<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SignInToSniff.Core/SignInToSniff.Core.csproj" />
    <ProjectReference Include="../../src/SignInToSniff.Proxy/SignInToSniff.Proxy.csproj" />
  </ItemGroup>
</Project>
