<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Titanium.Web.Proxy" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SignInToSniff.Core/SignInToSniff.Core.csproj" />
  </ItemGroup>
</Project>
